### ISSUE TITLE
RetroPie

### ISSUE THREAD

**Issue by boidacarapreta** [boidacarapreta/minecraft-pi#1]
Segundo a [documentação](https://retropie.org.uk/docs/), podem ser usados vários emuladores e controles, em especial [Xbox 360](https://retropie.org.uk/docs/Xbox-360-Controller/) (tenho 2 parados).

**Comment by ghost** [comment]
Foi testado o Xbox 360 Wireless Controller. Todos os botões, analógicos e digitais, funcionaram relativamente bem. Porém, em alguns momentos era necessário recalibração. No fim, não houve grande melhora na experiência de uso, sendo preferido o teclado com mouse.
